config/routes.rb
Locomotive::Engine.routes.draw do

  # authentication
  devise_for :locomotive_account,
    class_name:   'Locomotive::Account',
    path:         '',
    path_prefix:  nil,
    failure_app:  'Locomotive::Devise::FailureApp',
    controllers:  { sessions: 'locomotive/sessions', passwords: 'locomotive/passwords' }

  authenticated :locomotive_account do
    root to: 'pages#index'
  end

  devise_scope :locomotive_account do
    match '/'         => 'sessions#new'
    delete 'signout'  => 'sessions#destroy', as: :destroy_locomotive_session
  end

  root to: 'pages#index'

  resources :pages do
    put :sort, on: :member
    get :get_path, on: :collection
  end

  resources :snippets

  resources :sites

  resource :current_site, controller: 'current_site'

  resources :accounts

  resource :my_account, controller: 'my_account' do
    put :regenerate_api_key, on: :member
  end

  resources :memberships

  resources :theme_assets do
    get :all, action: 'index', on: :collection, defaults: { all: true }
  end

  resources :translations

  resources :content_assets

  resources :content_types

  resources :content_entries, path: 'content_types/:slug/entries' do
    put :sort,    on: :collection
    get :export,  on: :collection
  end

  # installation guide
  match '/installation'       => 'installation#show', defaults: { step: 1 }, as: :installation
  match '/installation/:step' => 'installation#show', as: :installation_step

end

Rails.application.routes.draw do

  # API
  namespace :locomotive, module: 'locomotive' do
    namespace :api do

      match 'documentation' => 'documentation#show'

      resources :tokens, only: [:create, :destroy]

      resource  :current_site, controller: 'current_site', only: [:show, :update, :destroy]

      resources :memberships, only: [:index, :show, :create, :update, :destroy]

      resource  :my_account, controller: 'my_account', only: :show

      with_options only: [:index, :show, :create, :update, :destroy] do |api|

        api.resources :accounts

        api.resources :sites

        api.resources :pages

        api.resources :snippets

        api.resources :content_types

        api.resources :content_entries, path: 'content_types/:slug/entries'

        api.resources :theme_assets

        api.resources :translations

        api.resources :content_assets
      end
    end
  end

  # sitemap
  match '/sitemap.xml'  => 'locomotive/public/sitemaps#show', format: 'xml'

  # robots.txt
  match '/robots.txt'   => 'locomotive/public/robots#show', format: 'txt'

  # public content entry submissions
  resources :locomotive_entry_submissions, controller: 'locomotive/public/content_entries', path: 'entry_submissions/:slug'

  # magic urls
  match '/_admin'               => 'locomotive/public/pages#show_toolbar'
  match ':locale/_admin'        => 'locomotive/public/pages#show_toolbar', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match ':locale/*path/_admin'  => 'locomotive/public/pages#show_toolbar', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match '*path/_admin'          => 'locomotive/public/pages#show_toolbar'

  match '/_edit'                => 'locomotive/public/pages#edit'
  match ':locale/_edit'         => 'locomotive/public/pages#edit', page_path: 'index', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match ':locale/*path/_edit'   => 'locomotive/public/pages#edit', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match '*path/_edit'           => 'locomotive/public/pages#edit'

  root to:                      'locomotive/public/pages#show'
  match ':locale'               => 'locomotive/public/pages#show', page_path: 'index', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match ':locale/*path'         => 'locomotive/public/pages#show', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match '*path'                 => 'locomotive/public/pages#show'
end

app/models/locomotive/extensions/shared/seo.rb
module Locomotive
  module Extensions
    module Shared
      module Seo
        extend ActiveSupport::Concern

        included do
          field :seo_title,         type: String, localize: true
          field :meta_keywords,     type: String, localize: true
          field :meta_description,  type: String, localize: true
        end

      end # Seo
    end # Shared
  end # Extensions
end # Locomotive

app/models/locomotive/extensions/shared/slug.rb
module Locomotive
  module Extensions
    module Shared
      module Slug
        extend ActiveSupport::Concern

        module ClassMethods

          def slugify_from(field)
            class_eval <<-EOV
              before_validation { |object| object.send(:normalize_slug, :#{field.to_s}) }
            EOV
          end
        end

        protected

        def normalize_slug(field)
          value = self.send(field)

          if self.slug.blank? && value.present?
            self.slug = value.clone
          end

          if self.slug.present?
            self.slug.permalink!
          end
        end

      end
    end
  end
end

app/views/locomotive/shared/menu/_contents.html.haml
= submenu_entry 'pages', pages_path do
  .wrapper
    - if can? :manage, @page
      .header
        %p
          = link_to new_page_path do
            %i.icon-plus
            = t('locomotive.pages.index.new')
    .inner
      %h2!= t('locomotive.pages.index.latest_entries')
      %ul
        - current_site.pages.unscoped.latest_updated.minimal_attributes.each do |page|
          %li
            %i.icon-chevron-right
            = link_to truncate(page.title, length: 25), edit_page_path(page)
            %span= time_ago_in_words(page.updated_at)

- each_content_type do |menu_item|
  -if menu_item.is_a?(Array)
    - content_types = menu_item
    = submenu_entry '...', '#', i18n: false do
      .wrapper
        .inner
          %ul.big-links
            - content_types.each do |content_type|
              %li
                = link_to truncate(content_type.name, length: 20), content_entries_path(content_type.slug)
  - else
    - content_type = menu_item
    = submenu_entry truncate(content_type.name, length: 15), content_entries_path(content_type.slug), i18n: false, css: "#{'on' if is_content_type_selected(content_type)}" do
      .wrapper
        .header
          %p
            = link_to new_content_entry_path(content_type.slug) do
              %i.icon-plus
              = t('locomotive.content_entries.index.new')

          - if can? :manage, content_type
            %p.edit
              = link_to edit_content_type_path(content_type) do
                %i.icon-pencil
                = t('locomotive.content_types.index.edit')

        .inner
          %h2!= t('locomotive.content_entries.index.latest_entries')
          %ul
            - content_type.entries.latest_updated.each do |entry|
              %li
                %i.icon-chevron-right
                = link_to truncate(entry._label(content_type), length: 20), edit_content_entry_path(content_type.slug, entry)
                %span= time_ago_in_words(entry.updated_at)