config/routes.rb
Locomotive::Engine.routes.draw do

  # authentication
  devise_for :locomotive_account,
    class_name:   'Locomotive::Account',
    path:         '',
    path_prefix:  nil,
    failure_app:  'Locomotive::Devise::FailureApp',
    controllers:  { sessions: 'locomotive/sessions', passwords: 'locomotive/passwords' }

  authenticated :locomotive_account do
    root to: 'pages#index'
  end

  devise_scope :locomotive_account do
    match '/'         => 'sessions#new'
    delete 'signout'  => 'sessions#destroy', as: :destroy_locomotive_session
  end

  root to: 'pages#index'

  resources :pages do
    put :sort, on: :member
    get :get_path, on: :collection
  end

  resources :snippets

  resources :sites

  resource :current_site, controller: 'current_site'

  resources :accounts

  resource :my_account, controller: 'my_account' do
    put :regenerate_api_key, on: :member
  end

  resources :memberships

  resources :theme_assets do
    get :all, action: 'index', on: :collection, defaults: { all: true }
  end

  resources :translations

  resources :content_assets

  resources :content_types

  resources :content_entries, path: 'content_types/:slug/entries' do
    put :sort,    on: :collection
    get :export,  on: :collection
  end

  # installation guide
  match '/installation'       => 'installation#show', defaults: { step: 1 }, as: :installation
  match '/installation/:step' => 'installation#show', as: :installation_step

end

Rails.application.routes.draw do

  # API
  namespace :locomotive, module: 'locomotive' do
    namespace :api do

      match 'documentation' => 'documentation#show'

      resources :tokens, only: [:create, :destroy]

      resource  :current_site, controller: 'current_site', only: [:show, :update, :destroy]

      resources :memberships, only: [:index, :show, :create, :update, :destroy]

      resource  :my_account, controller: 'my_account', only: :show

      with_options only: [:index, :show, :create, :update, :destroy] do |api|

        api.resources :accounts

        api.resources :sites

        api.resources :pages

        api.resources :snippets

        api.resources :content_types

        api.resources :content_entries, path: 'content_types/:slug/entries'

        api.resources :theme_assets

        api.resources :translations

        api.resources :content_assets
      end
    end
  end

  # sitemap
  match '/sitemap.xml'  => 'locomotive/public/sitemaps#show', format: 'xml'

  # robots.txt
  match '/robots.txt'   => 'locomotive/public/robots#show', format: 'txt'

  # public content entry submissions
  resources :locomotive_entry_submissions, controller: 'locomotive/public/content_entries', path: 'entry_submissions/:slug'

  # magic urls
  match '/_admin'               => 'locomotive/public/pages#show_toolbar'
  match ':locale/_admin'        => 'locomotive/public/pages#show_toolbar', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match ':locale/*path/_admin'  => 'locomotive/public/pages#show_toolbar', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match '*path/_admin'          => 'locomotive/public/pages#show_toolbar'

  match '/_edit'                => 'locomotive/public/pages#edit'
  match ':locale/_edit'         => 'locomotive/public/pages#edit', page_path: 'index', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match ':locale/*path/_edit'   => 'locomotive/public/pages#edit', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match '*path/_edit'           => 'locomotive/public/pages#edit'

  root to:                      'locomotive/public/pages#show'
  match ':locale'               => 'locomotive/public/pages#show', page_path: 'index', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match ':locale/*path'         => 'locomotive/public/pages#show', locale: /(#{Locomotive.config.site_locales.join('|')})/
  match '*path'                 => 'locomotive/public/pages#show'
end

app/models/locomotive/ability.rb
module Locomotive
  class Ability
    include CanCan::Ability

    ROLES = %w(admin designer author)

    def initialize(account, site)
      @account, @site = account, site

      alias_action :index, :show, :edit, :update, to: :touch

      if @site
        @membership = @site.memberships.where(account_id: @account.id).first
      elsif @account.admin?
        @membership = Membership.new(account: @account, role: 'admin')
      end

      if @membership.nil?
        setup_account_without_a_site
      elsif @membership.admin?
        setup_admin_permissions!
      else
        setup_default_permissions!

        setup_designer_permissions! if @membership.designer?

        setup_author_permissions!  if @membership.author?
      end
    end

    def setup_account_without_a_site
      cannot :manage, :all

      can :create, Site
    end

    def setup_default_permissions!
      cannot :manage, :all
    end

    def setup_author_permissions!
      can :touch, ThemeAsset

      can [:read, :create, :update], Page
      cannot :destroy, Page
      cannot :customize, Page

      can :manage, [ContentEntry, ContentAsset, Translation]

      can :touch, Site, _id: @site._id

      can :read, ContentType
    end

    def setup_designer_permissions!
      can :manage, Page

      can :manage, ContentEntry

      can :manage, ContentType

      can :manage, Snippet

      can :manage, ThemeAsset

      can :manage, ContentAsset

      can :manage, Translation

      can :manage, Site, _id: @site._id

      can :point, Site

      cannot :create, Site

      can :manage, Membership

      cannot :grant_admin, Membership

      cannot [:update, :destroy], Membership do |membership|
        @membership.account_id == membership.account_id || # can not edit myself
        membership.admin? # can not modify an administrator
      end
    end

    def setup_admin_permissions!
      can :manage, :all

      cannot [:update, :destroy], Membership do |membership|
        @membership.account_id == membership.account_id # can not edit myself
      end
    end
  end
end

app/models/locomotive/account.rb
module Locomotive
  class Account

    include Locomotive::Mongoid::Document

    devise *Locomotive.config.devise_modules

    ## devise fields (need to be declared since 2.x) ##
    field :remember_created_at,     type: Time
    field :email,                   type: String, default: ''
    field :encrypted_password,      type: String, default: ''
    field :authentication_token,    type: String
    field :reset_password_token,    type: String
    field :reset_password_sent_at,  type: Time
    field :password_salt,           type: String
    field :sign_in_count,           type: Integer, default: 0
    field :current_sign_in_at,      type: Time
    field :last_sign_in_at,         type: Time
    field :current_sign_in_ip,      type: String
    field :last_sign_in_ip,         type: String

    ## attributes ##
    field :name
    field :locale,  default: Locomotive.config.default_locale.to_s or 'en'
    field :api_key

    ## protected attributes ##
    attr_protected :api_key

    ## validations ##
    validates_presence_of :name

    ## associations ##

    ## callbacks ##
    before_validation :api_key_should_not_be_empty
    before_destroy    :remove_memberships!

    ## scopes ##
    scope :ordered, order_by(name: :asc)

    ## indexes ##
    index({ email: 1 }, { unique: true, background: true })

    ## methods ##

    def sites
      @sites ||= Site.where('memberships.account_id' => self._id)
    end

    # Tell if the account has admin privileges or not.
    # Actually, an account is considered as an admin if
    # it owns at least one admin membership in all its sites.
    #
    # @return [ Boolean ] True if admin
    #
    def admin?
      Site.where(memberships: { '$elemMatch' => { account_id: self._id, role: :admin } }).count > 0
    end

    # Regenerate the API key without saving the account.
    #
    # @return [ String ] The new api key
    #
    def regenerate_api_key
      self.api_key = Digest::SHA1.hexdigest("#{self._id}-#{Time.now.to_f}-#{self.created_at}")
    end

    # Regenerate the API key AND then save the account.
    #
    def regenerate_api_key!
      self.regenerate_api_key
      self.save
    end

    # Create the API token which will be passed to all the requests to the Locomotive API.
    # It requires the credentials of an account with admin role OR the API key of the site.
    # If an error occurs (invalid account, ...etc), this method raises an exception that has
    # to be caught somewhere.
    #
    # @param [ String ] email The email of the account
    # @param [ String ] password The password of the account
    # @param [ String ] api_key The API key of the site.
    #
    # @return [ String ] The API token
    #
    def self.create_api_token(email, password, api_key)
      if api_key.present?
        account = self.where(api_key: api_key).first

        raise 'The API key is invalid.' if account.nil?
      elsif email.present? && password.present?
        account = self.where(email: email.downcase).first

        raise 'Invalid email or password.' if account.nil? || !account.valid_password?(password)
      else
        raise 'The request must contain either the user email and password OR the API key.'
      end

      account.ensure_authentication_token!

      account.authentication_token
    end

    # Logout the user responding to the token passed in parameter from the API.
    # An exception is raised if no account corresponds to the token.
    #
    # @param [ String ] token The API token created by the create_api_token method.
    #
    # @return [ String ] The API token
    #
    def self.invalidate_api_token(token)
      account = self.where(authentication_token: token).first

      raise 'Invalid token.' if account.nil?

      account.reset_authentication_token!

      token
    end

    def devise_mailer
      Locomotive::DeviseMailer
    end

    protected

    def api_key_should_not_be_empty
      if self.api_key.blank?
        self.regenerate_api_key
      end
    end

    def password_required?
      !persisted? || !password.blank? || !password_confirmation.blank?
    end

    def remove_memberships!
      self.sites.each do |site|
        membership = site.memberships.where(account_id: self._id).first

        if site.admin_memberships.size == 1 && membership.admin?
          raise ::I18n.t('errors.messages.needs_admin_account')
        else
          membership.destroy
        end
      end
    end

  end
end

app/models/locomotive/content_asset.rb
module Locomotive
  class ContentAsset

    include Locomotive::Mongoid::Document

    ## extensions ##
    include Extensions::Asset::Types
    include Extensions::Asset::Vignette
    include Locomotive::Cloudflare::Asset

    ## fields ##
    field :content_type,  type: String
    field :width,         type: Integer
    field :height,        type: Integer
    field :size,          type: Integer
    field :position,      type: Integer, default: 0

    ## associations ##
    belongs_to :site, class_name: 'Locomotive::Site', validate: false, autosave: false

    ## validations ##
    validates_presence_of :source

    ## behaviours ##
    mount_uploader :source, ContentAssetUploader, mount_on: :source_filename

    ## scopes ##
    scope :ordered,     order_by(created_at: :desc)
    scope :by_filename, ->(query) { where(source_filename: /.*#{query}.*/i) }

    ## callbacks ##
    after_save            :expire_cache

    ## methods ##

    alias :name :source_filename

    def extname
      return nil unless self.source?
      File.extname(self.source_filename).gsub(/^\./, '')
    end

    def to_liquid
      { url: self.source.url }.merge(self.attributes).stringify_keys
    end

  end
end

app/models/locomotive/editable_control.rb
module Locomotive
  class EditableControl < EditableElement

    ## fields ##
    field :content
    field :options, type: Array,   default: []

    ## methods ##

    def options=(value)
      if value.respond_to?(:split)
        value = value.split(/\s*\,\s*/).map do |option|
          first, last = *option.split(/\s*=\s*/)
          last ||= first
          { 'value' => first, 'text' => last }
        end
      end

      super(value)
    end

    def default_content?
      false
    end

    def copy_attributes_from(el)
      super(el)

      %w(content options).each do |meth|
        self.attributes[meth] = el.attributes[meth]
      end
    end

    protected

    def propagate_content
      if self.content_changed?
        operations  = {
          '$set' => {
            'editable_elements.$.content' => self.content,
            'editable_elements.$.options' => self.options,
          }
        }

        self.page.collection.find(self._selector).update(operations, multi: true)
      end
      true
    end

  end
end

app/models/locomotive/editable_element.rb
module Locomotive
  class EditableElement

    # include ::Mongoid::Document
    include Locomotive::Mongoid::Document

    ## fields ##
    field :slug
    field :block
    field :hint
    field :priority,          type: Integer, default: 0
    field :fixed,             type: Boolean, default: false
    field :disabled,          type: Boolean, default: false, localize: true
    field :from_parent,       type: Boolean, default: false
    field :locales,           type: Array,   default: []

    ## associations ##
    embedded_in :page, class_name: 'Locomotive::Page', inverse_of: :editable_elements

    ## validations ##
    validates_presence_of :slug

    ## callbacks ##
    after_save :propagate_content, if: :fixed?

    ## scopes ##
    scope :by_priority, order_by(priority: :desc)

    ## methods ##

    def disabled?
      !!self.disabled # the original method does not work quite well with the localization
    end

    def disabled_in_all_translations?
      return self.disabled_translations if self.disabled_translations.is_a?(Boolean)
      return false if disabled_translations.blank?
      self.disabled_translations.all? { |_, v| v == true }
    end

    # Determines if the current element can be edited in the back-office
    #
    def editable?
      !self.disabled? &&
      self.locales.include?(::Mongoid::Fields::I18n.locale.to_s) &&
      (!self.fixed? || !self.from_parent?) &&
      !self.destroyed?
    end

    def _run_rearrange_callbacks
      # callback from page/tree. not needed in the editable elements
    end

    def default_content?
      # needs to be overridden for each kind of elements
      true
    end

    # Copy attributes extracted from the corresponding Liquid tag
    # Each editable element overrides this method.
    #
    # @param [ Hash ] attributes The up-to-date attributes
    #
    def copy_attributes(attributes)
      # _type is among the mass-assign protected attributes.
      if type = attributes.delete(:_type)
        self._type = type
      end

      self.attributes = attributes
    end

    # Copy attributes from an existing editable element coming
    # from the parent page. Each type of an editable element may or not
    # override this method. The source element is a new record.
    #
    # @param [ EditableElement] el The source element
    #
    def copy_attributes_from(el)
      self.attributes   = el.attributes.reject { |attr| !%w(slug block hint priority fixed disabled locales from_parent).include?(attr) }
      self.from_parent  = true
    end

    # Copy the default attributes: _type, hint, fixed, priority and locales
    # from an existing editable element coming from the parent page.
    # Each type of an editable element may or not override this method for
    # options for instance.
    #
    # @param [ EditableElement] el The source element
    #
    def copy_default_attributes_from(el)
      # only the type, hint and fixed properties can be modified from the element
      %w(_type hint fixed priority locales).each do |attr|
        self.send(:"#{attr}=", el.send(attr.to_sym))
      end
    end

    # Set the default content from an existing editable element coming
    # from the parent page. Each editable element may or not
    # override this method. The source element is an existing record.
    def set_default_content_from(el)
      self.add_current_locale
    end

    # Make sure the current locale is added to the list
    # of locales for the current element so that we know
    # in which languages the element was translated.
    #
    def add_current_locale
      locale = ::Mongoid::Fields::I18n.locale.to_s
      self.locales << locale unless self.locales.include?(locale)
    end

    # Set the content of the editable element with a default value
    # only if the content has not already been modified by the user.
    #
    # @param [ String ] content The default content.
    #
    def content_from_default=(content)
      # needs to be overridden for each kind of elements
    end

    protected

    def _selector
      locale = ::Mongoid::Fields::I18n.locale
      {
        'site_id'                         => self.page.site_id,
        "template_dependencies.#{locale}" => { '$in' => [self.page._id] },
        'editable_elements.fixed'         => true,
        'editable_elements.block'         => self.block,
        'editable_elements.slug'          => self.slug,
      }
    end

    # Update the value (or content) of the elements matching the same block/slug
    # as the current element in all the pages inheriting from the current page.
    # This method is called only if the element has the "fixed" property set to true.
    # It also needs to be overridden for each kind of elements (file, short text, ...etc)
    #
    def propagate_content
      true
    end

  end
end

app/models/locomotive/editable_long_text.rb
module Locomotive
  class EditableLongText < EditableText
    # @deprecated
  end
end

app/views/locomotive/theme_assets/_asset.html.haml
%script{ type: 'text/html', id: 'editable_theme_asset_item' }

  %strong= link_to "{{local_path}}", edit_theme_asset_path('asset_id').gsub(/\/asset_id\//, '/{{id}}/')
  .more
    %span.size {{size}}
    %span!= t('.updated_at')
    %span.date {{updated_at}}

    {{#if can_be_deleted}}
    = link_to_icon :trash, '#', class: 'remove', data: { confirm: t('locomotive.messages.confirm') }
    {{/if}}

app/views/locomotive/theme_assets/_form.html.haml
- content_for :head do
  = render '/locomotive/theme_assets/picker'

- content_for :backbone_view_data do
  :plain
    theme_asset: #{escape_json @theme_asset.persisted? ? @theme_asset.to_json.html_safe : 'null'}

= f.hidden_field :performing_plain_text

#file-selector{ class: "selector #{'hidden' if display_plain_text?(@theme_asset)}" }
  = f.inputs name: :information do
    = f.input :source

  - if allow_plain_text_editing?(@theme_asset)
    = link_to '#', class: 'alt' do
      %i.icon-share
      = t('locomotive.theme_assets.form.choose_plain_text')

- if allow_plain_text_editing?(@theme_asset)
  #text-selector{ class: "selector #{'hidden' unless display_plain_text?(@theme_asset)}", style: "#{'display: none' unless display_plain_text?(@theme_asset)}" }
    = f.inputs name: :code, class: 'inputs code' do

      - if @theme_asset.new_record?
        = f.input :plain_text_name

        = f.input :plain_text_type, as: 'select', collection: %w(stylesheet javascript), include_blank: false

      = f.input :plain_text, as: :'Locomotive::Code', type: plain_text_type(@theme_asset)

    = link_to '#', class: 'alt' do
      %i.icon-share
      = t('locomotive.theme_assets.form.choose_file')

= f.inputs name: :options, class: "inputs foldable #{'folded' if inputs_folded?(@theme_asset)}" do
  = f.input :folder

app/views/locomotive/theme_assets/_list.html.haml
%script{ type: 'text/html', id: "#{name}_list" }

  %h3!= title
  .inner
    %p.no-items{ style: 'display: none' }!= empty_message

    %ul{ class: name.dasherize }

app/views/locomotive/theme_assets/_picker.html.haml
%script{ type: 'text/html', id: 'theme_image_picker' }

  %h2!= t('locomotive.theme_assets.image_picker.title')

  %p.no-items{ style: 'display: none' }!= t('locomotive.theme_assets.image_picker.no_items')

  %ul.list{ style: 'display: none' }

  .dialog-actions
    = link_to t('locomotive.buttons.close'), '#', id: 'close-link'

    .button-wrapper.upload
      = form_tag theme_assets_path(:json), class: 'quick-upload' do
        = file_field_tag 'theme_asset[source]', multiple: 'multiple'
        = link_to t('locomotive.theme_assets.image_picker.upload'), theme_assets_path(:json), class: 'new', id: 'upload-link'

%script{ type: 'text/html', id: 'theme_asset' }

  %li.item
    = link_to '{{local_path}}', '{{url}}'
    .more
      %span.size {{size}}
      &mdash;
      %span!= t('.updated_at')
      %span.date {{updated_at}}

app/views/locomotive/theme_assets/edit.html.haml
- title t('.title', file: @theme_asset.source_filename)

- content_for :submenu do
  = render_cell 'locomotive/settings_menu', :show

- if can?(:manage, Locomotive::ThemeAsset)
  - content_for :buttons do
    = local_action_button t('locomotive.theme_assets.index.new'), new_theme_asset_path, icon: 'icon-plus'

%p.help
  - if %w(image javascript stylesheet).include?(@theme_asset.content_type.to_s)
    != t(".help_#{@theme_asset.content_type}", path: @theme_asset.local_path(true), width: @theme_asset.width, height: @theme_asset.height)

  != t('.help', url: @theme_asset.source.url)


= semantic_form_for @theme_asset, url: theme_asset_path(@theme_asset), html: { multipart: true, class: 'save-with-shortcut' } do |form|

  = render 'form', f: form

  = render 'locomotive/shared/form_actions', back_url: theme_assets_path, button_label: :update

app/views/locomotive/theme_assets/index.html.haml
- title t('.title')

- content_for :head do
  = render 'asset'

  = render 'list', name: 'images', title: t('.images'), empty_message: t('.no_items', url: new_theme_asset_path)
  = render 'list', name: 'media', title: t('.media'), empty_message: t('.no_items', url: new_theme_asset_path)
  = render 'list', name: 'others', title: t('.others'), empty_message: t('.no_items', url: new_theme_asset_path)

  - if can?(:manage, Locomotive::Snippet)
    = render '/locomotive/snippets/snippet'
    = render 'list', name: 'snippets', title: t('.snippets'), empty_message: t('locomotive.snippets.index.no_items', url: new_snippet_path)

  - if can?(:manage, Locomotive::ThemeAsset)
    = render 'list', name: 'js_and_css', title: t('.css_and_js'), empty_message: t('.no_items', url: new_theme_asset_path)
    = render 'list', name: 'fonts', title: t('.fonts'), empty_message: t('.no_items', url: new_theme_asset_path)

- content_for :backbone_view_data do
  :plain
    snippets:           #{escape_json can?(:manage, Locomotive::Snippet) ? @snippets.map { |snippet| snippet.to_presenter.as_json_for_html_view }.to_json.html_safe : 'null'},
    images:             #{escape_json theme_assets_to_json(@assets[:images]).html_safe},
    media:              #{escape_json theme_assets_to_json(@assets[:media]).html_safe},
    others:             #{escape_json theme_assets_to_json(@assets[:others]).html_safe},
    js_and_css_assets:  #{escape_json can?(:manage, Locomotive::ThemeAsset) ? theme_assets_to_json(@js_and_css_assets).html_safe : 'null'},
    fonts:              #{escape_json can?(:manage, Locomotive::ThemeAsset) ? theme_assets_to_json(@assets[:fonts]).html_safe : 'null'}

- content_for :submenu do
  = render_cell 'locomotive/settings_menu', :show

- content_for :buttons do
  - if can?(:manage, Locomotive::ThemeAsset)
    = form_tag theme_assets_path(:json), id: 'theme-assets-quick-upload', class: 'quick-upload', :'data-sending-form-message' => t('locomotive.messages.sending_form')  do
      = file_field_tag 'theme_asset[source]', multiple: 'multiple'
      = local_action_button :quick_upload, '#', icon: :upload, class: 'new'

  = local_action_button t('locomotive.snippets.index.new'), new_snippet_path, icon: 'icon-plus' if can?(:manage, Locomotive::Snippet)
  = local_action_button :new, new_theme_asset_path, icon: :plus if can?(:manage, Locomotive::ThemeAsset)

%p!= t('.help')

- if can?(:manage, Locomotive::Snippet)
  #snippets-anchor

- if can?(:manage, Locomotive::ThemeAsset)
  #js-and-css-anchor

#images-anchor

- if can?(:manage, Locomotive::ThemeAsset)
  #fonts-anchor

#media-anchor

#others-anchor

app/views/locomotive/theme_assets/new.html.haml
- title t('.title')

- content_for :submenu do
  = render_cell 'locomotive/settings_menu', :show

%p!= t('.help')

= semantic_form_for @theme_asset, url: theme_assets_path, html: { multipart: true } do |form|

  = render 'form', f: form

  = render 'locomotive/shared/form_actions', back_url: theme_assets_path, button_label: :create